### PR TITLE
Catalog bulk action  - HIGH TESTS

### PR DESCRIPTION
**Pull request by fouratachour**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | Develop
| Description?  | Development of  HIGH test  (Catalog bulk action part) with the new architecture
| Type?         | new feature
| Category?     | TE
| BC breaks?    | no
| Deprecations? | no

### CODE REVIEW

**Comment by marionf** [comment]
Hello @fouratachour 
I see twice the "Enable the product list" but I don't see the "delete" in bulk action.
In addition to checking the presence of confirmation messages, we need to check if the action was done well:
- After deletion, we need to verify if the products are not there anymore
- After duplication, we need to verify if the products duplicated are well here 
- After the disable action, we need to verify if the products are not displayed in FO
- After the enable action, we need to verify if the products are displayed in FO

**Comment by fatmaBouchekoua** [comment]
Hello @marionf ,
This PR is very old, after this one we have created another to add the "delete" bulk actions and remove the second "Enable product list" 
- After deletion, we are verifying that the products are not there anymore in the BO
- After duplication, we are verifying that the products are well duplicated (the number of the products was well increased to double)
- For the disable and enable action, we didn't check them in the FO because you didn't do it in the video (and when we create this PR and the new one there are no testlink scenarios)

**Comment by marionf** [comment]
Thank you for your answer @fatmaBouchekoua 
What is the PR with the delete in bulk ?
We need to adapt the PRs following the scenario on testlink & check results in FO following the actions

**Comment by fouratachour** [comment]
Hello @marionf 
This is the PR with the delete in bulk https://github.com/PrestaShop/PrestaShop/pull/8812

**Pull request merged**
